"""Add premium subscription and float stars

Revision ID: ad23da8e4b67
Revises: 
Create Date: 2026-09-10 06:43:52.317096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad23da8e4b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('star_transfers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('recipient_student_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('stars',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_star_transfers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_star_transfers_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_star_transfers_recipient_student_id'), ['recipient_student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_star_transfers_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_questions_test_id'), ['test_id'], unique=False)

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_tests_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('premium_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('student_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('stars',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)

    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawals_user_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_status'))
        batch_op.drop_index(batch_op.f('ix_withdrawals_created_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_student_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.alter_column('stars',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('student_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('premium_expires')
        batch_op.drop_column('is_premium')

    with op.batch_alter_table('tests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tests_subject_id'))
        batch_op.drop_index(batch_op.f('ix_tests_level'))
        batch_op.drop_index(batch_op.f('ix_tests_created_by'))
        batch_op.drop_index(batch_op.f('ix_tests_created_at'))

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_questions_test_id'))

    with op.batch_alter_table('star_transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_star_transfers_sender_id'))
        batch_op.drop_index(batch_op.f('ix_star_transfers_recipient_student_id'))
        batch_op.drop_index(batch_op.f('ix_star_transfers_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_star_transfers_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stars',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('recipient_student_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
